export const ALBUM_LIST_REQUEST = 'ALBUM_LIST_REQUEST'
export const ALBUM_LIST_SUCCESS = 'ALBUM_LIST_SUCCESS'
export const ALBUM_LIST_FAIL = 'ALBUM_LIST_FAIL'

export const ALBUM_DETAILS_REQUEST = 'ALBUM_DETAILS_REQUEST'
export const ALBUM_DETAILS_SUCCESS = 'ALBUM_DETAILS_SUCCESS'
export const ALBUM_DETAILS_FAIL = 'ALBUM_DETAILS_FAIL'

export const ALBUM_CREATE_REQUEST = 'ALBUM_CREATE_REQUEST'
export const ALBUM_CREATE_SUCCESS = 'ALBUM_CREATE_SUCCESS'
export const ALBUM_CREATE_FAIL = 'ALBUM_CREATE_FAIL'

export const ALBUM_DELETE_REQUEST = 'ALBUM_DELETE_REQUEST'
export const ALBUM_DELETE_SUCCESS = 'ALBUM_DELETE_SUCCESS'
export const ALBUM_DELETE_FAIL = 'ALBUM_DELETE_FAIL'
